baseURL: "flopiloop.github.io" 
title: Jonathan WILD
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true


taxonomies:
    tag: tags

menu:
    main:
        - name: Compétences
          url: Compétences/
          weight: 5 
        - name: Projets
          url: projets/
          weight: 2
 

params:
    description: "Etudiant @UGA & @IUT2 Grenoble"
    author: WILD Jonathan
    DateFormat: "January 2006"
    hideFooter: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    defaultTheme: auto 
    disableThemeToggle: false
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jonathan WILD
          subtitle: "Etudiant @UGA & @IUT2 Grenoble"
          imageUrl: "pp_website.png"
          imageWidth: 220 
          imageHeight: 220 
          buttons:
            - name: "CV (FR)"
              url: "CV(FR).pdf"
            - name: "CV (EN)"
              url: "CV(ENG).pdf"
            - name: Projets / Projects
              url: "projets/"
            - name: Compétences / Skills
              url: "competences/"


    socialIcons:
        - name: Email
          url: jonathan.wild.2005@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/jonathan-wild-b7986434a/
        - name: GitHub
          url: https://github.com/flopiloop


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jonathan WILD"
      icon: icon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true